[Feat] 꿈 기록 삭제 API 구현 및 삭제 로직 구현
TeamRecorDream/RecorDream-iOS pull request #101
Opened 2023-01-05 11:04 UTC by Suyeon9911

## 👻 작업한 내용
### 꿈 기록을 삭제 했을 경우의  API를 구현하였습니다 
1. 꿈 기록이 성공적으로 삭제 되었을 때, 서버에서 응답으로 204 noContent 가 넘어오게됩니다. 이 경우, 응답으로 받는 json 모델이 없기 때문에 따로 EmptyJson 메서드를 추가해서 처리해주었습니다! response에서 success 가 떴을 때 status code를 확인한 후 true 이벤트를 전달해주었습니다. 
2. 삭제 후 상세보기 모달을 dismiss 하게 될 경우, full screen modal 이 아니기 때문에 viewWillAppear 가 호출되지 않습니다. 삭제된 꿈 기록이 홈에 돌아가서도 그대로 남아있게 되고, 그 꿈기록을 누르면 오류가 나기 때문에 Notification을 사용해서 viewWillAppear가 호출되도록 하였습니다. -> 혹시 노티 말고 더 좋은 방법을 알고 계시다면 공유 부탁드립니다 ~~ 

## 🎤 PR Point

## 📸 스크린샷

|    구현 내용    |   스크린샷   |
| :-------------: | :----------: |
| 삭제 로직 영상  |![Simulator Screen Recording - iPhone 14 - 2023-01-05 at 19 58 22](https://user-images.githubusercontent.com/81313960/210765490-231e1d90-5cde-4601-af4c-4e41acece1bb.gif) |

## 📮 관련 이슈

- Resolved: #93

2023-01-05 11:57 UTC, Suyeon9911 commented
@L-j-h-c  [430f3ee](https://github.com/TeamRecorDream/RecorDream-iOS/pull/101/commits/430f3ee4d897bbf323defc5435d8f1f654f88ccc) -> 요 커밋에서 수정뷰랑 연결 시켜뒀습니다 !! 커밋 상세내역에 우선 설명 적어놨습니다.

2023-01-05 12:24 UTC, Suyeon9911 commented
수정 완료 후 viewWillAppear 호출 하도록 노티로 구현했습니다
다만 ,,, 수정 후에 다시 fetch 하면 뒤의 스크롤 뷰? 가 뱅글뱅글 돌아가는게 보이는 현상이 있습니다 

https://user-images.githubusercontent.com/81313960/210779852-0f48aa13-c220-4c07-9e74-a74e1d7edd2c.mp4

2023-01-05 13:22 UTC, L-j-h-c requested changes

2023-01-05 13:22 UTC, L-j-h-c commented on RecorDream-iOS/Projects/Modules/RD-Network/Sources/Foundation/BaseService.swift
> +    }
👍 👍

2023-01-05 13:22 UTC, L-j-h-c commented on RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetail/View/DreamDetailVC.swift
> +
👼

2023-01-05 13:22 UTC, L-j-h-c commented on RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetail/View/DreamDetailVC.swift
> +        self.bindViewModels()
bind를 viewWillAppear에서 하시는면 구독이 중복될 수 있어 위험합니다! viewDidLoad에서 하고 Input으로 ViewWillAppear Observable을 넣어주시면 됩니당!

2023-01-05 13:22 UTC, L-j-h-c commented on RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetail/View/DreamDetailVC.swift
> +        self.bindViewModels()
여기서 호출하신 건 수정하기에서 수정 직후에 상세보기에서 반영하기 위해서인가요?

2023-01-05 13:22 UTC, L-j-h-c commented on RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetail/View/DreamDetailVC.swift
> +    }
인위적으로 viewWillAppear를 호출하는 것보단 원하는 액션을 실행시켜주는 것이 좋을 것 같아요! viewWillAppear는 저희가 구현하고자 하는 기능보다 더 큰 기능을 호출하는 느낌이라... 사이드 이펙트가 있을 수 있다고 생각해요~!

2023-01-05 13:25 UTC, L-j-h-c commented
[언급하신 부분](https://github.com/TeamRecorDream/RecorDream-iOS/pull/101#issuecomment-1372151665)은 따로 이슈파서 수정하긴 해야겠네용... pageViewController 쓰기가 참 어려운 것 같아여..!

2023-01-06 05:30 UTC, Suyeon9911 commented on RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetail/View/DreamDetailVC.swift
> +
@L-j-h-c 👼🏻 super 메서드 호출.. memo..

2023-01-06 05:32 UTC, Suyeon9911 commented on RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetail/View/DreamDetailVC.swift
> +        self.bindViewModels()
@L-j-h-c 아 그러면 viewDidLoad에서 구독 중이기 때문에 viewWillAppear를 이벤트를 받아도 fetch가 되는건가요?? 아직 Rx에 대한 이해가 많이 부족하네유..

2023-01-06 05:33 UTC, Suyeon9911 commented on RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetail/View/DreamDetailVC.swift
> +        self.bindViewModels()
@L-j-h-c  넵 수정 이후에 상세보기에 바로 반영되는게 맞는것 같아서요 !! 현재 홈 뷰에서도 이런 방식으로 하고 있는데 수정해야겠네욜..

2023-01-06 05:38 UTC, Suyeon9911 commented on RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetail/View/DreamDetailVC.swift
> +    }
@L-j-h-c 흠 듣고보니 그렇긴하네용... 데이터를 fetch 하는 메서드를 호출하려면 뷰모델의 output에 다시 접근해야해서 viewWillAppear에 viewModel을 구독하는 메서드를 넣어두고 viewWillAppear를 호출해준 상태였는데 한번 다른 방법을 생각해봐야겠네요 !

2023-01-06 05:42 UTC, Suyeon9911 commented on RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetail/View/DreamDetailVC.swift
> +        self.bindViewModels()
@L-j-h-c 아 혹시  VC에 viewWillAppear Observable 을 따로 만들면 될까요..????

2023-01-06 05:45 UTC, L-j-h-c commented on RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetail/View/DreamDetailVC.swift
> +        self.bindViewModels()
@Suyeon9911 
bindViewModel에서 하는 일은 
Input : 뷰컨트롤러에서 받을 수 있는 인터랙션에 대한 이벤트를 방출하는 옵저버블(뷰컨이 소유)을 ViewModel에 전달하고
Output: 뷰모델은 구독한 이벤트를 처리하여 Output으로 내보내고, 이 Output을 뷰컨이 구독하고 있어요!

그래서 ViewDidLoad에서 서로의 구독관계를 한 번만 만들어주고, VIewWillAppear는 실제로 이벤트가 일어나기만 한다면 ViewWillAppear를 담당하는 옵저버블에서 이벤트를 뷰모델에 전달하게 됩니다. 만약에 바인드를 ViewWillAppear에서 하게되면, viewWillAppear가 일어나는 만큼 transform이 호출되겠죠? 그러면 subscribe도 중복이 되어 하나의 이벤트에 중복된 횟수의 로직이 처리되고 오류가 납니다!

2023-01-06 05:45 UTC, L-j-h-c commented on RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetail/View/DreamDetailVC.swift
> +        self.bindViewModels()
ViewWillAppear는 methodInvoked를 통해 처리할 수 있습니다!

<img width="554" alt="image" src="https://user-images.githubusercontent.com/77208067/210938212-52360f8d-4857-45cd-bcbe-8f7c74388fc9.png">

2023-01-06 06:09 UTC, Suyeon9911 commented on RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetail/View/DreamDetailVC.swift
> +        self.bindViewModels()
@L-j-h-c 오호 !! 자세한 설명 .. 감사드립니돠..

2023-01-06 06:51 UTC, Suyeon9911 commented on RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetail/View/DreamDetailVC.swift
> +        self.bindViewModels()
@L-j-h-c  [7406e98](https://github.com/TeamRecorDream/RecorDream-iOS/pull/101/commits/7406e98e5484d038b7b2f976cb009a7203147b60) 수정했습니당 !!

2023-01-06 06:57 UTC, Suyeon9911 commented
@L-j-h-c 중복구독의 문제였던것인지.. 빙글빙글 돌아가는 현상이 더이상 나타나지 않네요...... ㅇ.ㅇ...

2023-01-06 07:38 UTC, Suyeon9911 commented on RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetail/View/DreamDetailVC.swift
> +    }
@L-j-h-c  [2276259](https://github.com/TeamRecorDream/RecorDream-iOS/pull/101/commits/2276259be81aeed595fc1379c5e5b81f33786c37) 이렇게 했는데.. 음 머랄까.. 다시 홈뷰로 돌아갓을때도 이상하고  상세보기 뷰의 스크롤 돌아가는 문제도 있네요..

2023-01-06 07:38 UTC, Suyeon9911 commented on RecorDream-iOS/Projects/Presentation/Sources/MainTabBarScene/DreamDetail/View/DreamDetailVC.swift
> +    }
fetch가 2번되나>..?

2023-01-07 14:46 UTC, Suyeon9911 commented
@EunHee-Jeong  @L-j-h-c  Fetch 가 여러번되는 문제점을 찾아서 해결했습니다. Rx 이벤트 처리 관련이라고 생각했는데 알고보니 Notification Observer가 정상적으로 제거되지 않아서 그런거였더라구요 !! viewWillAppear에서 add 해주고, viewWillDisAppear에서 remove해주었습니다 !!

2023-01-07 14:51 UTC, EunHee-Jeong approved these changes
수고베라~~

2023-01-07 16:20 UTC, L-j-h-c approved these changes
수고하셨어요!

2023-01-08 04:10 UTC, merged